const {test}=require('node:test'),assert=require('node:assert/strict');const E=require('../dist/js/engine.js'),B=require('../dist/js/bank.js');
const zeros=()=>E.PRODUCTS.map(()=>0);
const assessment=(changes={})=>({score:90,grade:'A',eligible:true,rate:2,years:10,capacity:500000,workingNeed:1000000,short:{balance:0,available:1000000},equipment:{balance:0,available:5000000},...changes});
test('three purpose-based choices, no state mutation',()=>{const s=E.createState(),before=JSON.stringify(s);assert.deepEqual(B.quote(s,assessment()).amounts,[500000,1000000,1000000]);for(const need of [0,1,900,40000]){const q=B.quote(s,assessment({workingNeed:need}));assert.equal(q.amounts.length,3);assert(q.amounts.every(n=>Number.isSafeInteger(n)&&n>=0));assert(q.amounts[2]<=q.limit);}assert.equal(JSON.stringify(s),before);});
test('oversized, denied, pending and high score upsell are separate',()=>{const s=E.createState();assert.equal(B.assess(s,assessment(),'short',1200000).status,'excess');assert.equal(B.assess(s,assessment({score:null,eligible:false}),'short',500000).status,'pending');s.balances.役員貸付金=1000;const d=B.assess(s,assessment({score:40,eligible:false}),'short',500000);assert.equal(d.status,'denied');assert(d.reasons.some(r=>r.includes('資金分離')));assert.equal(B.assess(s,assessment(),'short',500000).upsell,1000000);assert.equal(B.assess(s,assessment({score:79,grade:'B'}),'short',500000).upsell,null);assert.equal(B.assess(s,assessment(),'short',1000000).upsell,null);});
test('short loan journals, no revenue, duplicate execution blocked, 3-month repayment',()=>{let s=E.createState(),cash=s.balances.預金;s=B.execute(s,assessment(),'short',800000);assert.equal(s.balances.預金,cash+800000);assert.equal(s.balances.短期借入金,800000);assert.equal(s.balances.売上高,0);assert.throws(()=>B.execute(s,assessment(),'short',100000));let r=E.run(s,E.recommend(s));assert.equal(r.report.borrowing,800000);assert.equal(r.report.debtService.interest,0);assert.equal(r.state.balances.預金,r.report.opening+r.report.inflow-r.report.outflow);s=E.next(r.state);for(let t=2;t<=4;t++){r=E.run(s,E.recommend(s));assert.equal(r.report.debtService.interest,1333);assert.equal(r.report.debtService.principal,t===4?800000:0);assert.equal(r.state.balances.預金,r.report.opening+r.report.inflow-r.report.outflow);E.assertState(r.state);s=E.next(JSON.parse(JSON.stringify(r.state)));}assert.equal(s.balances.短期借入金,0);assert.equal(s.loans[0].balance,0);});
test('equipment funding is bounded by cost and atomically buys asset',()=>{const s=E.createState(),a=assessment();assert.equal(B.assess(s,a,'freezer',1600000).status,'excess');const n=B.execute(s,a,'freezer',300000);assert.equal(n.balances.預金,s.balances.預金-1350000);assert(n.equipment.freezer);assert.equal(n.balances.長期借入金+n.balances['1年内返済予定長期借入金'],300000);assert.equal(n.actionLocked,'investment');let r=E.run(n,zeros());assert.equal(r.report.borrowing,300000);assert.equal(r.report.extra,1650000);r=E.run(E.next(r.state),zeros());assert.equal(r.report.debtService.principal,5000);assert.equal(r.report.debtService.interest,500);E.assertState(r.state);});
test('rejection and changed conditions never move money',()=>{const s=E.createState(),before=JSON.stringify(s);assert.throws(()=>B.execute(s,assessment({eligible:false,score:40}),'short',100000));assert.throws(()=>B.execute(s,assessment(),'tank',100000));assert.equal(JSON.stringify(s),before);const closed=E.run(s,zeros()).state;assert.throws(()=>B.execute(closed,assessment(),'short',100000));});
test('startup support adds back recorded interest once and caps cumulative advances',()=>{let s=E.createState();s.turn=15;s.history=[{turn:12,balances:{売上原価:1500000}},{turn:13,balances:{売上高:62000,支払利息:12000},monthProfit:50000,interestExpense:12000},{turn:14,balances:{売上高:124000,支払利息:24000},monthProfit:50000,interestExpense:12000}];s.loans=[{kind:'equipment',amount:1200000,balance:1200000,rate:12,months:120,start:1,due:121,payment:10000}];s.balances.長期借入金=1080000;s.balances['1年内返済予定長期借入金']=120000;s.balances.預金+=1200000;const a=assessment({score:35,eligible:false,grade:'D',rate:5,short:{balance:0,available:0},equipment:{balance:1200000,available:0}});assert.equal(B.quote(s,a,'startup').limit,1500000);s.loans.push({kind:'startup',amount:1000000,balance:200000,rate:5,months:60,start:1,due:61,payment:16667});s.balances.長期借入金+=100000;s.balances['1年内返済予定長期借入金']+=100000;s.balances.預金+=200000;const q=B.quote(s,a,'startup');assert.equal(q.limit,500000);assert.equal(q.amounts[2],q.limit);assert.equal(B.assess(s,a,'startup',600000).status,'excess');});
