const {test}=require('node:test');const assert=require('node:assert/strict');const E=require('../dist/js/engine.js');const zeros=()=>E.PRODUCTS.map(()=>0);
test('opening assets and stock agree; no employees',()=>{const s=E.createState();assert.equal(s.balances.預金,7063520);assert.equal(s.balances.商品,1196800);assert.equal(s.staff.length,0);assert.equal(E.usage(s).dry/4,1885);E.assertState(s);});
test('normal month product mix and P/L',()=>{let s=E.createState();const r=E.run(s,zeros(),'list','tend',{noise:1,season:1});assert.equal(r.report.cashSales+r.report.cardSales,1468390);assert.equal(r.report.monthProfit,-136760);assert.equal(r.report.cardSales,93060);assert.equal(r.state.inventory[1],476);E.assertState(r.state);});
test('card receipts t+2, never booked as another sale',()=>{let s=E.createState();let a=E.run(s,zeros(),'list','tend',{noise:1,season:1});assert.equal(a.report.collected,0);s=E.next(a.state);let b=E.run(s,zeros(),'list','hire',{noise:1,season:1});assert.equal(b.report.collected,0);s=E.next(b.state);let c=E.run(s,zeros(),'list','hire',{noise:1,season:1});assert.equal(c.report.collected,93060);assert.equal(c.report.cardSales,0);});
test('equipment purchase atomic, warehouse asset/capacity/maintenance',()=>{let s=E.createState();const before=JSON.stringify(s);let w=E.buy(s,'warehouse');assert.equal(JSON.stringify(s),before);assert.equal(w.balances.建物附属設備,3000000);assert.equal(E.capacities(w).dry,16000);assert.equal(E.upkeep(w),10000);assert.throws(()=>E.buy(w,'warehouse'));const r=E.run(w,zeros());assert.equal(r.report.served,650);assert.equal(r.report.extra,3300000);assert.equal(r.report.fixedCash,713500);assert.equal(r.state.balances.預金,r.report.opening+r.report.inflow-r.report.outflow);E.assertState(r.state);});
test('unlock, capacity limits and overdraft rejection',()=>{const s=E.createState(),q=zeros();q[6]=1;assert.match(E.validation(s,q),/設備/);assert.throws(()=>E.buy(s,'tank'));const f=E.buy(s,'freezer');q[6]=0;q[5]=601;assert.match(E.validation(f,q),/上限/);q[5]=600;assert.equal(E.validation(f,q),'');q[5]=0;q[0]=99999;assert.match(E.validation(f,q),/上限/);const broke=structuredClone(s);broke.balances.預金=1;assert.throws(()=>E.buy(broke,'warehouse'));});
test('aji deaths, FIFO, inventory and cash journal amounts',()=>{let s=E.buy(E.createState(),'freezer');s=E.next(E.run(s,zeros()).state);s=E.buy(s,'tank');const q=zeros();q[6]=200;s.actionLocked='hire';let r=E.run(s,q);assert.equal(r.state.inventory[6],190);assert.equal(r.report.waste,800);assert.equal(r.report.served,0);assert.equal(r.state.balances.商品,E.PRODUCTS.reduce((v,p,i)=>v+r.state.inventory[i]*p.cost,0));E.assertState(r.state);});
test('demand cap and independent staffing limit',()=>{const s=E.createState();s.attraction=1.5;let r=E.run(s,zeros(),'list','tend',{noise:1,season:1.2});assert.equal(r.report.visitors,950);assert.equal(r.report.served,950);s.equipment={warehouse:true,freezer:true,tank:true};assert.equal(E.limits(s).cap,1600);assert.equal(E.limits(s).service,1000);});
test('constant seeds, save/restore and 24 month ledger invariants',()=>{let a=E.createState(),b=structuredClone(a);for(let t=1;t<=24;t++){const q=E.recommend(a);let ra=E.run(a,q),rb=E.run(b,q);assert.deepEqual(ra,rb);E.assertState(ra.state);if(ra.state.ended)throw Error('standard policy failed at '+t);a=E.next(ra.state);b=E.next(JSON.parse(JSON.stringify(rb.state)));}assert.equal(a.turn,25);assert.equal(a.history.length,24);});
test('expiry six months, no monthly ambient bait disposal',()=>{let s=E.createState();for(let t=1;t<=6;t++){let r=E.run(s,zeros(),'list','hire',{noise:1,season:1});assert.equal(r.state.inventory[1],1100);s=E.next(r.state);}assert.equal(s.turn,7);assert.equal(s.inventory[1],0);assert(s.pendingEntries.some(e=>e.memo.includes('期限切れ')));E.assertState(s);});
test('duplicate month cannot execute and recommendation fits limits',()=>{let s=E.createState();const q=E.recommend(s);assert.equal(E.validation(s,q),'');let r=E.run(s,q);assert.throws(()=>E.run(r.state,q));});

test('physical sizes, fixed durable prices and slow turnover',()=>{const s=E.createState(),q=zeros();q[2]=37;assert.match(E.validation(s,q),/上限/);assert.deepEqual(s.inventory.slice(2,5),[3,60,3]);assert(E.PRODUCTS[2].space>E.PRODUCTS[4].space&&E.PRODUCTS[4].space>E.PRODUCTS[1].space);assert.equal(E.PRODUCTS[0].space,E.PRODUCTS[3].space);for(const price of ['list','sale','plus10']){const r=E.run(s,zeros(),price,'tend',{noise:1,season:1});assert.equal(r.report.productResults.filter(p=>['rod','reel'].includes(p.id)).reduce((n,p)=>n+p.cardNet+p.cardTax,0),88000);assert.equal(r.report.counts[2],1);assert.equal(r.report.counts[4],1);}});
test('each hiring role changes service and monthly salary',()=>{for(const [role,service,wage] of [['manager',900,350000],['employee',800,250000],['parttime',400,120000]]){const s=E.hire(E.createState(),role);assert.equal(E.limits(s,'hire').service,service);const r=E.run(s,zeros(),'list','hire',{noise:1,season:1});assert.equal(r.state.balances.給料手当,wage);assert.equal(r.report.fixedCash,702500+wage+(role==='parttime'?0:Math.floor(wage*.15)));E.assertState(r.state);}assert.throws(()=>E.hire(E.createState(),'que'));});

test('April statements retain the true March close as comparison',()=>{let s=E.createState();for(let t=1;t<=12;t++){const a=[8,11].includes((t-1)%12+1)?'improve':'tend';s=E.run(s,E.recommend(s,a),'list',a,{noise:1}).state;if(t<12)s=E.next(s);}const march={...s.balances};s=E.next(s);const april=E.run(s,E.recommend(s),'list','tend',{noise:1}).report;assert.deepEqual(april.previousClose,march);assert.notDeepEqual(april.previousClose,april.before);assert.equal(april.after.繰越利益剰余金-april.previousClose.繰越利益剰余金,E.profit(march));});
test('recommendation accounts for the selected price demand',()=>{const s=E.createState(),value=s.inventory[0]*E.PRODUCTS[0].cost;s.inventory[0]=0;s.lots[0]=[];s.balances.商品-=value;s.balances.預金+=value;const list=E.recommend(s,'tend','list'),sale=E.recommend(s,'tend','sale'),markup=E.recommend(s,'tend','plus10');assert(sale[0]>list[0]);assert(markup[0]<list[0]);assert.equal(sale[2],list[2]);E.assertState(s);});
