const test=require('node:test'),assert=require('node:assert/strict');const E=require('../dist/js/engine.js'),X=E.extension,B=require('../dist/js/backup.js');
const bank={eligible:true,grade:'A',rate:2,score:90};
function rich(turn=25){const s=E.createState();s.turn=turn;s.balances.預金+=100000000;s.balances.資本金+=100000000;s.opening={...s.balances};s.previousClose={...s.balances};s.owner=10000000;s.history=[{turn:12,balances:{売上高:15000000,減価償却費:1000000}},{turn:24,balances:{売上高:18000000,減価償却費:1000000}}];return s;}
function run(s,action='tend'){return E.run(s,E.recommend(s,action),'list',action,{noise:1});}
function cashCheck(r){assert.equal(r.report.opening+r.report.inflow-r.report.outflow,r.state.balances.預金);assert.equal(r.report.segments.ordinary,E.ordinary(r.report.after)-E.ordinary(r.report.before));E.assertState(r.state);}
test('correlated property candidates are stable, bounded and age-finance sensitive',()=>{const s=rich();const orig=JSON.stringify(s);for(let t=25;t<120;t+=3){s.turn=t;const ps=X.market(s);assert.deepEqual(ps,X.market(structuredClone(s)));for(const p of ps){assert(p.price>0&&p.rent>0&&p.land+p.building===p.price);assert(p.yieldRate>.039&&p.yieldRate<.141);assert(p.taxLife>=2);const q=X.finance(s,p,bank);assert(q.months<=300);assert(q.months<=p.financeLife*12);assert(q.limit<=p.price*.9);assert(X.finance(s,p,{...bank,eligible:false}).limit===0);}}s.turn=25;assert.equal(JSON.stringify(s),orig);});
test('purchase is atomic; tenant deposit, rent, VAT, debt and depreciation reconcile',()=>{let s=rich(),p=X.market(s)[0],q=X.finance(s,p,bank);const old=JSON.stringify(s);assert.throws(()=>X.buyProperty(s,p.id,q.limit+10000,bank));assert.equal(JSON.stringify(s),old);s=X.buyProperty(s,p.id,Math.min(1000000,q.limit),bank);assert.equal(s.balances.土地,p.land);assert.equal(s.balances.賃貸建物,p.type==='building'?p.building:E.gross(s,p.building));let r=run(s);cashCheck(r);s=E.next(E.compact(r.state));r=run(s);cashCheck(r);assert.equal(r.state.balances.土地,p.land);assert(r.report.entries.filter(e=>e.type==='depreciation'&&e.assetId===p.id).every(e=>e.segmentId===p.segmentId));assert.equal(r.state.balances.預り敷金,r.state.expansion.properties[0].deposit);const rent=r.report.entries.find(e=>e.type==='rentIncome');if(rent){assert.equal(rent.segmentId,p.segmentId);assert.equal(r.report.entries.some(e=>e.type==='vatOutput'&&e.segmentId===p.segmentId),p.type==='building');}});
test('fish crew are separate; catches conserve quantity and fixed costs remain in rest',()=>{let s=X.buyFishery(rich(),0,bank);for(let i=0;i<36;i++){const r=run(s);cashCheck(r);s=E.next(E.compact(r.state));if(s.expansion.fishery.crew.length+s.staff.length>=3)break;for(const p of [...s.staff])if(!s.actionLocked||s.storeDutyTurn===s.turn)s=X.transferStaff(s,p.id,'boat');if(E.recruitment(s).open){if(s.storeDutyTurn===s.turn)s=X.transferStaff(s,s.expansion.fishery.crew[0].id,'store');s=X.hireCrew(s,s.expansion.fishery.crew.length+s.staff.length?'crew':'captain');}}s=E.next(E.compact(run(s).state));for(const p of [...s.staff])s=X.transferStaff(s,p.id,'boat');assert.equal(s.staff.length,0);assert.equal(s.expansion.fishery.crew.length,3);assert.throws(()=>X.hireCrew(s,'captain'));s=X.setFishing(s,'rest');const r=run(s);cashCheck(r);const f=r.state.expansion.fishery;assert.equal(f.last.quantity,f.last.lost+f.last.sold);assert.equal(f.last.days,0);assert(r.report.entries.some(e=>e.segmentId==='fishery'&&e.debit==='給料手当'));});
test('forecast is read-only and fish acquisition forecasts crew ramp',()=>{const s=rich(),before=JSON.stringify(s),r=X.forecastExpansion(s,{kind:'fishery',amount:0},bank);assert.equal(r.error,undefined);assert.equal(r.rows.length,12);assert(r.rows.some(r=>r.segments.rows.some(x=>x.id==='fishery'&&x.sales>0)));assert.equal(JSON.stringify(s),before);});
function ending(){const s=rich(120);s.closed=true;s.history=[96,108,120].map(turn=>({turn,balances:{売上高:20000000,売上原価:10000000,減価償却費:2000000}}));X.prepareMA(s);return s;}
test('M&A has two offers, stable price, exact-once personal receipt, no corporate mutation',()=>{const s=ending(),m=s.expansion.ma;assert(m.initial<m.ceiling);assert.equal(X.score({...s,turn:119}),null);const before=JSON.stringify(s.balances);let n=X.negotiate(s,'discuss');n=X.negotiate(n,'offer',10);assert.equal(n.expansion.ma.attempts.length,1);assert.throws(()=>X.negotiate(n,'accept'));n=X.negotiate(n,'offer',10);assert.equal(n.expansion.ma.phase,'failed');assert.throws(()=>X.negotiate(n,'offer',1));n=X.negotiate(s,'accept');n=X.negotiate(n,'confirm');assert.equal(n.owner,s.owner+m.initial);assert.equal(JSON.stringify(n.balances),before);assert.throws(()=>X.negotiate(n,'confirm'));assert.equal(X.score(n).personal,n.owner+n.balances.役員借入金);assert.equal(X.score(n).sale,m.initial);});
test('tax selections are once per year; skim targets cash sales; choices preserve cash identity',()=>{let s=E.createState();s=X.chooseTaxPolicy(s,['skim','fiction','privateGear'],true);assert.throws(()=>X.chooseTaxPolicy(s,[],false));const r=run(s);cashCheck(r);assert(r.state.taxEvidence.some(e=>e.kind==='skim'&&e.base>0));assert.equal(X.taxEstimate(r.state).income,E.ordinary(r.state.balances));});
test('inventory and sale timing restore before next month sales; April report includes the reversal',()=>{let s=rich(1);s.history=[];s=X.chooseTaxPolicy(s,['inventory','defer']);for(let t=1;t<=12;t++){let r=run(s);cashCheck(r);s=r.state;if(t<12)s=E.next(E.compact(s));}assert(s.expansion.concealedInventory>0);const deferred=s.balances.繰延売上;assert(deferred>0);s=E.next(E.compact(s));assert.equal(s.expansion.concealedInventory,0);assert.equal(s.balances.繰延売上,0);E.assertState(s);cashCheck(run(s));});
test('audit correction respects saved decisions, penalties, personal tax and no repeated charge',()=>{let s=rich(25);s.expansion.auditScheduled=36;s.taxEvidence=[{id:'f1',turn:12,kind:'fiction',base:500000,vat:0,privateBenefit:500000,severe:true,status:'open'}];s.turn=36;s.opening={...s.balances};let r=run(s);assert(r.report.audit);const closed=JSON.stringify(r.state.balances);s=X.resolveFinding(r.state,'f1','explain');assert.equal(JSON.stringify(s.balances),closed);const owner=s.owner;s=E.next(s);assert.equal(s.taxEvidence[0].status,'assessed');assert.equal(s.owner,owner-100000);assert.equal(s.taxAudits.at(-1).penaltyRate,.35);const again=E.next(s);assert.equal(again.owner,s.owner);cashCheck(run(s));});
test('cruise reproduces single turns with fixed quantities and leaves source untouched',()=>{const s=rich(25),q=E.recommend(s),before=JSON.stringify(s),c=X.cruise(s,q,'list',12);assert.equal(JSON.stringify(s),before);let n=structuredClone(s);for(const row of c.rows){const r=E.run(n,q,'list',n.actionLocked||'tend');cashCheck(r);assert.equal(r.state.balances.預金,row.cash);if(row.turn===c.state.turn){assert.deepEqual(r.state.balances,c.state.balances);break;}n=E.next(E.compact(r.state));}assert(c.rows.length>0);});
test('UI renders investment, department, tax, cruise and M&A screens without mutation',()=>{const {boot}=require('./helpers/ui.cjs'),app=boot();app.run('skipIntro();state='+JSON.stringify(rich())+';showDiversification()');assert.match(app.get('shopDialogBody').innerHTML,/不動産/);app.run("investmentPlanView('fishery');el('expansionAmount').value='0';previewExpansion('fishery','fishery-boat')");assert.match(app.get('expansionPlanResult').innerHTML,/船長/);app.run('showTaxPolicy();showSegments();showCruise()');assert.match(app.get('shopDialogBody').innerHTML,/巡航|仕入数量/);app.run('state='+JSON.stringify(ending())+';showFinalResult()');assert.match(app.get('shopDialogBody').innerHTML,/kare.png/);});
test('timing reassessment taxes the missing year and releases next-year income once',()=>{const s=E.createState();s.turn=30;s.balances.預金+=10000000;s.balances.売上高+=10000000;s.taxAnnual=[{turn:12,income:1000000,assessed:320000},{turn:24,income:3000000,assessed:820000}];s.taxEvidence=[{id:'timing',turn:12,kind:'defer',base:1000000,vat:0,status:'open',severe:true}];const a={};E.assessTaxEvidence(s,a);assert.equal(a.corporateAdditional,0);assert.equal(a.taxChanges[0].additionalTax,250000);assert.equal(a.taxChanges[1].additionalTax,-250000);assert.equal(a.penalty,87500);assert.equal(s.taxLosses.length,0);const again={};E.assessTaxEvidence(s,again);assert.equal(again.additionalTax,undefined);E.assertState(s);});
test('expanded saves round-trip including closed pending audit, acquired asset and M&A result',()=>{let s=E.createState(),r;s.officerSalary=120000;s.livingCost=120;for(let t=1;t<=25;t++){if(t===25){s=E.lendByOwner({...s,owner:40000000},30000000);s=X.buyProperty(s,X.market(s)[0].id,0,bank);}r=run(s);s=r.state;if(t<25)s=E.next(E.compact(s));}const payload={version:7,state:s,choice:{quantities:E.PRODUCTS.map(()=>0),price:'list',action:'tend'},lastReport:r.report,seen:[],introComplete:true};const imported=B.decode(B.encode(payload));assert.deepEqual(imported.state.expansion.properties,s.expansion.properties);const broken=structuredClone(payload);broken.state.expansion.properties[0].building=-1;assert.throws(()=>B.validate(broken));});
