const {test}=require('node:test'),assert=require('node:assert/strict');const E=require('../dist/js/engine.js'),P=require('../dist/js/planning.js');
test('VAT is excluded from profit and inventory, included in bank/card cash and settles without duplicate tax',()=>{let s=E.createState();assert.equal(s.balances.仮払消費税等,239680);assert.equal(s.balances.資本金,10000000);assert.equal(s.balances.商品,1196800);let assessed;for(let t=1;t<=14;t++){const r=E.run(s,E.recommend(s),'list','tend',{noise:1});s=r.state;assert.equal(r.report.opening+r.report.inflow-r.report.outflow,s.balances.預金);E.assertState(s);if(t===12){assessed=r.report.consumption.assessed;assert(assessed>0);assert.equal(s.balances.仮受消費税等,0);assert.equal(s.balances.仮払消費税等,0);assert.equal(s.balances.未払消費税等,assessed);}if(t===14){assert.equal(r.report.consumption.paid,assessed);assert.equal(s.balances.未払消費税等,0);}if(t<14)s=E.next(E.compact(s)||s);}});
test('VAT refund and interim prepayment clear correct accounts without affecting P/L',()=>{const s=E.blankState();s.turn=12;s.balances.仮払消費税等=200000;s.balances.仮受消費税等=50000;const before=E.profit(s.balances);assert.equal(E.settleVAT(s).assessed,-150000);assert.equal(s.balances.未収消費税等,150000);s.turn=14;assert.equal(E.settleVAT(s).refund,150000);assert.equal(s.balances.未収消費税等,0);assert.equal(E.profit(s.balances),before);const n=E.blankState();n.turn=12;n.balances.仮受消費税等=1000000;E.settleVAT(n);assert(n.vatDue.some(x=>x.interim&&x.due===20&&x.amount===500000));n.turn=20;E.settleVAT(n);assert.equal(n.balances.仮払消費税中間納付,500000);n.turn=24;n.balances.仮受消費税等=300000;assert.equal(E.settleVAT(n).assessed,-200000);assert.equal(n.balances.仮払消費税中間納付,0);assert.equal(n.balances.未収消費税等,200000);assert.equal(n.balances.未払消費税等,0);});
test('obsolescence removes only old lots and records disposal loss not second cash payment',()=>{let s=E.createState();s.turn=12;s.closed=true;s.lots[3].push({turn:12,quantity:2});s.inventory[3]+=2;s.balances.商品+=1560;s.balances.預金-=1560;const cash=s.balances.預金;s=E.next(s);assert.equal(s.inventory[3],2);assert(s.pendingEntries.some(e=>e.memo.includes('陳腐化')&&e.debit==='商品廃棄損'&&e.amount===60*780));assert.equal(s.balances.預金,cash);E.assertState(s);});
test('owner lending conserves total cash and is liability, not revenue',()=>{let s=E.createState();s.owner=300000;const cash=s.owner+s.balances.預金;const n=E.lendByOwner(s,200000);assert.equal(n.owner+n.balances.預金,cash);assert.equal(n.balances.役員借入金,200000);assert.equal(E.profit(n.balances),0);assert.throws(()=>E.lendByOwner(s,400000));const r=E.run(n,E.recommend(n),'list','tend',{noise:1});assert.equal(r.report.opening+r.report.inflow-r.report.outflow,r.state.balances.預金);E.assertState(r.state);});
test('investment comparisons are read-only, seasonal and include VAT, loans and 24 monthly rows',()=>{const s=E.createState(),before=JSON.stringify(s);const r=P.compare(s,{equipment:'freezer',months:24,loan:500000,rate:5,term:60,hire:'none',effort:'quarterly'});assert.equal(JSON.stringify(s),before);for(const v of Object.values(r)){assert(!v.error);assert.equal(v.rows.length,24);}assert(r.investment.rows[1].repayment>0);assert(r.investment.rows.some(x=>x.tax>0));assert(r.downside.endCash<r.investment.endCash);assert.notEqual(r.investment.endCash,r.baseline.endCash);});
test('legacy migration adds VAT accounts prospectively and preserves past balances and rules',()=>{const s=E.createState();delete s.vatEnabled;delete s.rulesVersion;s.version=5;const cash=s.balances.預金;E.migrate(s);assert(s.vatEnabled);assert.equal(s.version,6);assert.equal(s.rulesVersion,'v22');assert.equal(s.balances.預金,cash);assert.equal(E.createState().rulesVersion,'v23');});

test('equipment-only comparison preserves hiring and reports distinct stop states',()=>{const s=E.createState(),plan={equipment:'none',hire:'parttime',months:12,price:'list',effort:'none'},r=P.compare(s,plan);assert.equal(r.baseline.profit,r.investment.profit);assert.deepEqual(r.baseline.rows,r.investment.rows);assert.equal(r.baseline.status,'completed');assert.equal(r.baseline.minimumCash,Math.min(...r.baseline.rows.map(x=>x.cash)));const invalid=P.simulate(s,{equipment:'tank',months:12});assert.equal(invalid.status,'invalidPlan');assert.equal(invalid.ended,false);});
