const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const E=require('../dist/js/engine.js'),X=E.extension,R=require('../dist/js/replay.js'),U=require('../dist/js/underwriting.js');
const seed=73129;
test('recorded browser commands reproduce server books, settings, salary and supply exactly',()=>{const {boot}=require('./helpers/ui.cjs'),app=boot();app.run(`skipIntro();state=Ranked.create(${seed});state.replay={id:'test',seed:${seed},ops:[]};state=E.playerSettings(state,{livingCost:200,payInterest:true});state=Expansion.setSalary(state,300000);state=E.run(state,E.recommend(state),'list','tend').state;state=E.next(state);state=E.run(state,E.recommend(state),'list','tend').state;`);const ops=JSON.parse(app.run('JSON.stringify(state.replay.ops)'));let s=R.create(seed);for(const op of ops)s=R.apply(s,op).state;assert.deepEqual(s.balances,JSON.parse(app.run('JSON.stringify(state.balances)')));assert.equal(s.owner,app.run('state.owner'));assert.equal(s.turn,2);assert.equal(ops.length,5);});
test('server rejects forged loan terms, direct cash editing and random demand overrides',()=>{let s=R.create(seed);assert.throws(()=>R.apply(s,{op:'fundLoan',args:[{amount:999999999,rate:1,months:120,kind:'equipment'}]}));assert.throws(()=>R.apply(s,{op:'settings',args:[{owner:1000000000}]}));assert.throws(()=>R.apply(s,{op:'run',args:[E.recommend(s),'list','tend',{noise:100}]}));assert.throws(()=>R.apply(s,{op:'property',args:['fake',0,{eligible:true,grade:'A'}]}));assert.throws(()=>R.apply(s,{op:'bankLoan',args:['short',1000000]}));});
test('self supply conserves fish quantity, physical inventory and company/department ledgers without VAT',()=>{let s=R.create(seed);s.turn=25;s.owner=100000000;s=E.lendByOwner(s,40000000);s=E.buy(s,'freezer');s.actionLocked=null;s=E.buy(s,'tank');s.actionLocked=null;s=X.buyFishery(s,0,U.assess(s));s.expansion.fishery.crew=[{id:'c',role:'captain',hiredTurn:24,wage:350000},{id:'a',role:'crew',hiredTurn:24,wage:180000},{id:'b',role:'crew',hiredTurn:24,wage:180000}];s=X.setSupply(s,300);s.opening={...s.balances};s.pendingEntries=[];let r=E.run(s,E.PRODUCTS.map(()=>0),'list','tend',{noise:1});const f=r.state.expansion.fishery.last;assert(f.transfer>0);assert.equal(Math.round(f.quantity*10),Math.round(f.sold*10)+f.lost*10+f.transfer);assert.equal(r.state.inventory[6],f.transfer);assert.equal(r.report.opening+r.report.inflow-r.report.outflow,r.state.balances.預金);assert(!r.report.entries.some(e=>e.type==='fisheryTransfer'&&(e.credit==='売上高'||e.debit==='仮払消費税等')));const transfer=r.report.entries.find(e=>e.type==='fisheryTransfer');assert.equal(transfer.credit,'売上原価');assert.equal(transfer.amount,f.transfer*80);assert.equal(r.report.segments.ordinary,E.ordinary(r.report.after)-E.ordinary(r.report.before));s=E.next(E.compact(r.state));assert(E.recommend(s)[6]<300);E.assertState(s);});
function fakeDB(){
 const {DatabaseSync}=require('node:sqlite'),db=new DatabaseSync(':memory:');
 db.exec(fs.readFileSync('drizzle/0000_loud_harry_osborn.sql','utf8'));
 function prepare(sql){return {bind(...args){return {
  async first(){return db.prepare(sql).get(...args)||null;},
  async all(){return {results:db.prepare(sql).all(...args)};},
  async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}
 };}};}
 return {db,prepare,async batch(items){db.exec('BEGIN');try{const r=[];for(const item of items)r.push(await item.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}};
}
test('API validates each step, isolates browsers, deduplicates retries, publishes computed results and supports withdrawal',async()=>{const worker=(await import('../worker/index.mjs')).default,DB=fakeDB(),env={DB},origin='https://game.test';const req=(path,data,cookie='')=>worker.fetch(new Request(origin+path,{method:data?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie},body:data?JSON.stringify(data):undefined}),env);let response=await req('/api/scenario'),scenario=await response.json();response=await req('/api/start',{scenario:scenario.scenario});const cookie=response.headers.get('Set-Cookie').split(';')[0],run=await response.json();assert.equal(run.seed,scenario.seed);let s=R.create(run.seed),cmd={op:'run',args:[E.recommend(s),'list','tend']};response=await req('/api/run/'+run.id+'/step',{revision:0,command:cmd},cookie);assert.equal(response.status,200);assert.equal((await response.json()).revision,1);response=await req('/api/run/'+run.id+'/step',{revision:0,command:cmd},cookie);assert.equal((await response.json()).duplicate,true);assert.equal(DB.db.prepare('SELECT COUNT(*) n FROM verified_operations').get().n,1);assert.equal((await req('/api/run/'+run.id+'/step',{revision:1,command:{op:'settings',args:[{owner:999999}]}},cookie)).status,422);assert.equal((await req('/api/run/'+run.id)).status,404);assert.equal((await req('/api/run/'+run.id+'/publish',{revision:1,name:'test',score:300},cookie)).status,422);
 // Fixture reaches final stage server-side; client still cannot submit balances or score.
 s.turn=120;s.closed=true;s.expansion.ma={phase:'ineligible',attempts:[]};s.history=Array.from({length:10},(_,i)=>({turn:(i+1)*12,balances:{...s.balances}}));const expected=X.score(s).total;DB.db.prepare('UPDATE verified_runs SET state = ? WHERE id = ?').run(JSON.stringify(s),run.id);response=await req('/api/run/'+run.id+'/publish',{revision:1,name:'クエ',score:9999,balances:{預金:999999999}},cookie);assert.equal(response.status,200);assert.equal((await response.json()).score,expected);const listed=await (await req('/api/ranking?scenario='+scenario.scenario)).json();assert.equal(listed.rows.length,1);assert.equal(listed.rows[0].score,expected);assert.equal((await req('/api/ranking/'+run.id)).status,200);assert.equal((await req('/api/run/'+run.id+'/withdraw',{},cookie)).status,200);assert.equal((await (await req('/api/ranking?scenario='+scenario.scenario)).json()).rows.length,0);
});
test('120-month client operations replay to identical score and bounded canonical record',()=>{let client=R.create(seed),server=R.create(seed),log=[];for(let t=1;t<=120;t++){const action=[8,11].includes((t-1)%12+1)?'improve':'tend',op={op:'run',args:[E.recommend(client,action),'list',action]};log.push(op);client=E.run(client,...op.args).state;server=R.apply(server,op).state;assert.equal(client.balances.預金,server.balances.預金);assert.equal(client.owner,server.owner);assert(!client.ended);if(t<120){client=E.next(E.compact(client));server=R.apply(server,{op:'next',args:[]}).state;}for(const e of server.entries){delete e.before;delete e.after;delete e.memo;}}assert.deepEqual(X.score(client),X.score(server));assert(Buffer.byteLength(JSON.stringify(server))<1800000);});
test('shared underwriting agrees with displayed scoring for original and diversified balance sheets',()=>{const {boot}=require('./helpers/ui.cjs'),app=boot();let s=R.create(seed);for(let t=1;t<=24;t++){const a=[8,11].includes((t-1)%12+1)?'improve':'tend';s=E.run(s,E.recommend(s,a),'list',a).state;if(t<24)s=E.next(E.compact(s));}app.run('state='+JSON.stringify(s));const ui=JSON.parse(app.run('JSON.stringify(bankAssessment(annualSeries(),state.balances))')),shared=U.assess(s);assert.equal(ui.score,shared.score);assert.equal(ui.capacity,shared.capacity);assert.equal(ui.equipment.limit,shared.equipment.limit);});
