const test=require('node:test'),assert=require('node:assert/strict'),E=require('../dist/js/engine.js'),B=require('../dist/js/bank.js'),U=require('../dist/js/underwriting.js'),R=require('../dist/js/replay.js');
const a={score:80,grade:'A',eligible:true,rate:2,years:10,capacity:1000000,workingNeed:2000000,short:{limit:2000000,balance:500000,available:1500000},equipment:{available:10000000,balance:0}};
function due(){let s=E.fundLoan(E.createState(),{amount:500000,rate:2,months:3,kind:'short'});s.turn=3;s.pendingBorrowing=0;s.pendingEntries=[];s.opening={...s.balances};return s;}
test('short loans mature in three months; same renewal is free even after another action',()=>{assert.equal(B.quote(E.createState(),a).months,3);let s=due();s.actionLocked='improve';const n=B.renew(s,a,0,500000);assert.equal(n.actionLocked,'improve');assert.equal(n.loans[0].due,7);assert.equal(n.balances.預金,s.balances.預金);});
test('reduction repays only the difference, without consuming action',()=>{const s=due(),n=B.renew(s,a,0,300000);assert.equal(n.actionLocked,null);assert.equal(n.balances.預金,s.balances.預金-200000);assert.equal(n.balances.短期借入金,300000);E.assertState(n);});
test('increase consumes action whether approved or denied; rejection never changes principal',()=>{const s=due(),yes=B.renew(s,a,0,700000),no=B.renew(s,a,0,3000000);assert.equal(yes.actionLocked,'bank');assert.equal(yes.balances.預金,s.balances.預金+200000);assert.equal(no.actionLocked,'bank');assert.equal(no.renewalDecision.status,'denied');assert.deepEqual(no.loans,s.loans);assert.equal(no.balances.預金,s.balances.預金);assert.throws(()=>B.renew(no,a,0,600000));});
test('loss with positive cash earnings retains equipment funding; cash losses need working-asset support',()=>{const balances={預金:3000000,商品:1000000,売掛金:1000000,資本金:5000000,繰越利益剰余金:0};const series=[{p:{売上高:12000000,売上原価:6000000,雑費:5500000,減価償却費:1000000}}];let x=U.bankAssessment(series,balances);assert.equal(x.latestCashFlow,500000);assert(x.equipment.available>0);const bad=U.bankAssessment([{p:{売上高:12000000,売上原価:6000000,雑費:6500000,減価償却費:1000000}}],balances);assert.equal(bad.equipment.available,0);assert(bad.short.available>0);const excess=U.bankAssessment([{p:{売上高:12000000,雑費:13000000}}],{...balances,商品:10000000});assert.equal(excess.short.available,0);});
test('startup support can accept accounting losses with positive monthly cash earnings',()=>{const s=E.createState();s.turn=15;s.history=[{turn:12,balances:{雑費:1500000}},{turn:13,balances:{売上高:100000,減価償却費:150000}},{turn:14,balances:{売上高:200000,減価償却費:300000}}];const d=B.startupSupport(s,a,'startup');assert(d.eligible);assert.equal(d.startupMonths[0].cashFlow,100000);assert(d.startupMonths[0].profit<0);s.history[2].balances.雑費=200000;assert.equal(B.startupSupport(s,a,'startup').eligible,false);});
test('reduced renewal appears once in monthly cash flows and principal repayments',()=>{let s=due();s=B.renew(s,a,0,300000);const {state,report}=E.run(s,E.PRODUCTS.map(()=>0));assert.equal(report.debtService.principal,200000);assert.equal(report.opening+report.inflow-report.outflow,state.balances.預金);const next=E.next(state);assert.equal(E.run(next,E.PRODUCTS.map(()=>0)).report.debtService.principal,0);assert.throws(()=>B.renew({...due(),actionLocked:'sales'},a,0,700000));});
test('increase accrues interest on the additional principal from the following month',()=>{const s=B.renew(due(),a,0,700000),r=E.run(s,E.PRODUCTS.map(()=>0));assert.equal(r.report.debtService.interest,833);const next=E.run(E.next(r.state),E.PRODUCTS.map(()=>0));assert.equal(next.report.debtService.interest,1166);assert.equal(r.report.opening+r.report.inflow-r.report.outflow,r.state.balances.預金);});
test('renewal denial consumes the turn in server replay as well',()=>{const s=due();s.turn=25;s.loans[0].due=26;s.history=[12,24].map(turn=>({turn,balances:{売上高:18000000,雑費:15000000}}));const n=R.apply(s,{op:'renew',args:[0,999000000]}).state;assert.equal(n.actionLocked,'bank');assert.equal(n.renewalDecision.status,'denied');assert.equal(n.loans[0].balance,500000);assert.throws(()=>R.apply(n,{op:'renew',args:[0,600000]}));});
test('renewal UI warns before the action is spent, and saves denial with action consumed',()=>{const {bootDOM}=require('./helpers/dom.cjs'),ui=bootDOM();try{const s=due();s.turn=25;s.loans[0].due=26;s.history=[12,24].map(turn=>({turn,balances:{売上高:18000000,雑費:15000000}}));ui.run(`state=${JSON.stringify(s)};introComplete=true;showBankConsultation()`);assert.equal(ui.run('state.actionLocked'),null);ui.click('[data-renew-loan="0"]');ui.document.getElementById('renewTarget').value='999000000';ui.click('[data-review-renew="0"]');assert.match(ui.document.getElementById('shopDialogBody').textContent,/否決でも戻りません/);assert.equal(ui.run('state.actionLocked'),null);ui.click('[data-confirm-renew="0"]');assert.equal(ui.run('state.actionLocked'),'bank');assert.equal(ui.run('state.renewalDecision.status'),'denied');assert.equal(ui.run('state.loans[0].balance'),500000);}finally{ui.close();}});
