const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../dist/js/engine.js'),R=require('../dist/js/replay.js');
function failing(){let s=R.create(73129),r;for(let t=1;t<=120;t++){const x=E.run(s,E.recommend(s),'list','tend');s=x.state;r=x.report;if(s.ended)break;s=E.next(E.compact(s));}return {s,r};}
test('cash shortfall suspends progress and owner funding rescues the same settled month',()=>{const {s,r}=failing();assert.equal(s.cashCrisis.status,'pending');assert.equal(E.next(s),s);const info=E.crisisInfo(s);assert(info.needed>0);const before=JSON.stringify(s),n=E.rescueOwner(s,info.needed);assert.equal(JSON.stringify(s),before);assert.equal(n.ended,false);assert.equal(n.cashCrisis.status,'resolved');assert.equal(n.turn,s.turn);assert.equal(E.profit(n.balances),E.profit(s.balances));assert.equal(n.owner,s.owner-info.needed);assert.equal(n.balances.役員借入金,info.needed);assert.equal(n.history.at(-1).balances.預金,n.balances.預金);const report=E.refreshRescueReport(n,r);assert.equal(report.opening+report.inflow-report.outflow,n.balances.預金);assert.throws(()=>E.rescueOwner(n,1));assert.equal(E.next(n).turn,s.turn+1);E.assertState(n);});
test('invalid inputs and declined funding do not change cash; explicit abandonment ends the opportunity',()=>{const {s}=failing(),before=JSON.stringify(s);for(const a of [0,-1,NaN,1.1,s.owner+1])assert.throws(()=>E.rescueOwner(s,a));assert.throws(()=>E.rescueBank(s,'fixture',10000));assert.equal(JSON.stringify(s),before);const n=E.abandonRescue(s);assert.equal(n.cashCrisis.status,'failed');assert(n.ended);assert.throws(()=>E.rescueOwner(n,1));});
test('partial owner contribution remains suspended and survives JSON reload',()=>{const {s}=failing();const n=E.rescueOwner(s,1);assert(n.ended);assert.equal(n.cashCrisis.status,'pending');const loaded=JSON.parse(JSON.stringify(n));assert.equal(E.rescueOwner(loaded,E.crisisInfo(loaded).needed).ended,false);});
test('rescue is replayable with no client-supplied loan approval',()=>{const {s}=failing(),a=E.crisisInfo(s).needed;assert.deepEqual(R.apply(s,{op:'rescueOwner',args:[a]}).state,E.rescueOwner(s,a));assert.throws(()=>R.apply(s,{op:'rescueBank',args:['fixture',10000]}));});
function creditworthy(){const s=E.createState();s.turn=25;s.closed=true;s.ended=true;s.cashCrisis={turn:25,status:'pending'};s.history=[12,24].map(turn=>({turn,balances:{売上高:18000000,売上原価:10000000,雑費:6000000}}));E.entry(s,'差入保証金','預金',s.balances.預金+100000,'検証用資金拘束');return s;}
test('bank approves only within real underwriting, books debt and does not charge same-month interest',()=>{const s=creditworthy();assert.equal(E.rescueOffer(s,'short',100000).status,'approved');assert.throws(()=>E.rescueBank(s,'short',10000000));const n=E.rescueBank(s,'short',100000);assert.equal(n.ended,false);assert.equal(n.balances.預金,0);assert.equal(n.balances.短期借入金,100000);assert.equal(n.loans[0].start,25);assert.equal(n.balances.支払利息,s.balances.支払利息);E.assertState(n);const partial=E.rescueBank(s,'short',50000);assert.equal(E.rescueOffer(partial,'short',50000).status,'denied');const mixed=E.rescueOwner({...partial,owner:100000},50000);assert.equal(mixed.ended,false);});
test('personal shortfall is booked once and insufficient rescue does not invent money',()=>{const s=creditworthy();s.owner=-30000;assert.equal(E.crisisInfo(s).needed,130000);const n=E.rescueBank(s,'short',130000);assert.equal(n.owner,0);assert.equal(n.balances.預金,0);assert.equal(n.balances.役員貸付金-s.balances.役員貸付金,30000);assert.equal(E.profit(n.balances),E.profit(s.balances));assert.throws(()=>E.rescueBank(n,'short',30000));});
test('late monthly receipts can fund the personal shortfall without unnecessary new borrowing',()=>{const s=creditworthy();E.entry(s,'預金','差入保証金',200000,'検証用返金');s.owner=-30000;assert.equal(E.crisisInfo(s).needed,0);const n=E.rescueOwner(s,0);assert.equal(n.owner,0);assert.equal(n.balances.預金,70000);assert.equal((n.loans||[]).length,0);assert.equal(n.ended,false);E.assertState(n);});
test('backup retains pending workout and month 120 can be rescued before final scoring',()=>{const Backup=require('../dist/js/backup.js'),{s,r}=failing();const payload={version:7,introComplete:true,state:s,lastReport:r,choice:{quantities:E.PRODUCTS.map(()=>0),price:'list',action:'tend'},seen:[]};const restored=Backup.decode(Backup.encode(payload)).state;assert.equal(restored.cashCrisis.status,'pending');assert.equal(E.rescueOwner(restored,E.crisisInfo(restored).needed).ended,false);const final=structuredClone(s);final.turn=120;final.cashCrisis.turn=120;assert.equal(E.extension.score(final),null);const n=E.rescueOwner(final,E.crisisInfo(final).needed);assert(E.extension.score(n));});
test('UI offers rescue instead of game over, and updates statements after funding',()=>{const {bootDOM}=require('./helpers/dom.cjs'),ui=bootDOM(),{s,r}=failing();try{ui.run(`state=${JSON.stringify(s)};lastReport=${JSON.stringify(r)};monthClosed=true;introComplete=true;renderPlanning()`);assert.equal(ui.document.getElementById('commit').disabled,false);ui.click('#commit');assert.match(ui.document.getElementById('shopDialogBody').textContent,/最後|不足/);ui.click('#rescueConsult');assert.match(ui.document.getElementById('shopDialogBody').textContent,/融資/);ui.click('#rescueBack');ui.click('#rescueOwnerSubmit');assert.equal(ui.run('state.cashCrisis.status'),'resolved');assert.equal(ui.run('state.ended'),false);assert.equal(ui.run('lastReport.after.預金'),ui.run('state.balances.預金'));assert.equal(ui.errors.length,0);}finally{ui.close();}});
