const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../dist/js/engine.js');
function annual(now,prior){const s=E.createState();s.turn=24;s.closed=true;s.balances={...s.balances,売上高:12000000,雑費:12000000-now};s.history=[{turn:12,balances:{売上高:12000000,雑費:12000000-prior}}];return [s,{turn:24,month:3,before:{},after:s.balances,monthProfit:now/12}];}
test('annual loss improvement is recognized without claiming profitability',()=>{const [s,r]=annual(-500000,-1500000),before=JSON.stringify(s);const c=E.queComment(s,r);assert.match(c.text,/赤字.*前年比.*改善/);assert.match(c.text,/100万円/);assert.equal(JSON.stringify(s),before);});
test('positive earnings can still deteriorate year over year',()=>{const c=E.queComment(...annual(100000,1000000));assert.match(c.text,/黒字.*前年比.*減/);});
test('a new loss is not described as a repeated loss',()=>{const c=E.queComment(...annual(-100000,100000));assert.match(c.text,/赤字に転じて/);assert.doesNotMatch(c.text,/も赤字/);});
test('first year never invents a year-over-year comparison',()=>{const [s,r]=annual(-500000,0);s.history=[];s.turn=r.turn=12;assert.match(E.queComment(s,r).text,/最初の/);assert.doesNotMatch(E.queComment(s,r).text,/前年比.*改善/);});
test('monthly review compares the same month and appears outside the old three-month cadence',()=>{const s=E.createState(),r={turn:14,month:5,monthProfit:-100000,before:{},after:s.balances};s.history=[{turn:2,monthProfit:-200000,balances:{}}];const c=E.queComment(s,r);assert.match(c.text,/前年同月.*改善/);assert.equal(E.queComment(s,{...r,provisional:true}),null);});
test('annual trend does not hide a due employee hint or urgent liquidity warning',()=>{const [s,r]=annual(-500000,-1500000);r.after.預金=1;r.staffHints=[{text:'ホフクさん、経理きっちりしてるな。'}];const text=E.queComment(s,r).text;assert.match(text,/前年比/);assert.match(text,/経理きっちり/);assert.match(text,/預金/);});
test('successive annual loss reductions are a trend, not a black-ink claim',()=>{const [s,r]=annual(-500000,-1000000);s.turn=r.turn=36;s.history=[{turn:12,balances:{雑費:1500000}},{turn:24,balances:{雑費:1000000}}];assert.match(E.queComment(s,r).text,/２年続けて赤字が縮んでる/);});
test('annual weaknesses use the actual waste and wage burden',()=>{const [s,r]=annual(-500000,-1500000);r.after.商品廃棄損=500000;assert.match(E.queComment(s,r).text,/捨てた商品/);r.after.商品廃棄損=0;r.after.給料手当=6000000;assert.match(E.queComment(s,r).text,/給料をまかなう売上/);});
test('ordinary annual close uses actual full-year results from the monthly engine',()=>{let s=E.createState(),r;for(let t=1;t<=24;t++){const action=[8,11].includes((t-1)%12+1)?'improve':'tend';const result=E.run(s,E.recommend(s,action),'list',action,{noise:1});s=result.state;r=result.report;if(t<24)s=E.next(E.compact(s));}const c=E.queComment(s,r);assert.equal(c.topic,'annualTrend');assert(c.comparison.current<0);assert(c.comparison.delta>0);assert.equal(c.comparison.current,E.profit(s.balances));assert.match(c.text,/前年比.*改善/);});
