const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../dist/js/engine.js'),X=E.extension,R=require('../dist/js/replay.js'),B=require('../dist/js/bank.js'),Backup=require('../dist/js/backup.js');
const bank={eligible:true,grade:'A',rate:2,short:{limit:50000}};
function rich(){let s=E.createState();s.turn=25;s.owner=80000000;s=E.lendByOwner(s,60000000);s.history=[12,24].map(turn=>({turn,balances:{売上高:20000000,売上原価:10000000,減価償却費:1000000}}));s.opening={...s.balances};s.pendingEntries=[];s.pendingBorrowing=0;return s;}
function run(s){return E.run(s,E.recommend(s,s.actionLocked||'tend'),'list',s.actionLocked||'tend',{noise:1});}
function check(r){E.assertState(r.state);assert.equal(r.report.opening+r.report.inflow-r.report.outflow,r.state.balances.預金);assert.equal(r.report.segments.profit,E.profit(r.report.after)-E.profit(r.report.before));}
test('v43 salary granularity, fixed living cost, old settings cannot restore exploit',()=>{assert.throws(()=>X.setSalary(E.createState(),123457));assert.throws(()=>E.playerSettings(E.createState(),{livingCost:120}));let s=E.createState();s.livingCost=120;const r=run(s);assert.equal(r.state.owner,40000);assert.equal(E.migrate(s).livingCost,200);});
test('v43 officer debt reduces wealth and health, scoring averages three fiscal years',()=>{const s=rich();s.turn=120;s.closed=true;s.history=[96,108,120].map((turn,i)=>({turn,balances:{売上高:20000000,売上原価:10000000+i*1000000}}));const original=X.score(s);assert.equal(original.ordinary,9000000);E.entry(s,'役員貸付金','預金',5000000,'test');E.entry(s,'未収利息','受取利息',100000,'test');const result=X.score(s);assert.equal(result.personal,original.personal-5100000);assert(result.health<original.health);});
test('v43 rescue caps amount and reserves next action',()=>{let s=rich();s.closed=true;s.ended=true;s.cashCrisis={turn:s.turn,status:'pending'};E.entry(s,'差入保証金','預金',s.balances.預金+100001,'test');assert.equal(E.rescueOffer(s,'short',120000).status,'denied');const offer=E.rescueOffer(s,'short',110000);assert.equal(offer.status,'approved');s=E.rescueBank(s,'short',110000);assert.equal(E.next(s).actionLocked,'bank');assert.deepEqual(s.rescueBankYears,[3]);});
test('v43 partial short reduction above current limit is allowed and paid exactly once',()=>{let s=E.fundLoan(E.createState(),{amount:100000,rate:2,months:3,kind:'short'});s.turn=3;s.actionLocked=null;const cash=s.balances.預金;s=B.renew(s,{...bank,eligible:false},0,80000);assert.equal(s.renewalDecision.status,'approved');assert.equal(s.balances.預金,cash-20000);assert.equal(s.loans[0].balance,80000);assert.equal(s.actionLocked,null);E.assertState(s);});
test('v43 residential acquisition capitalizes tax and takes no input credit',()=>{const s=rich(),p=X.market(s).find(p=>p.type!=='building');assert(p);const n=X.buyProperty(s,p.id,0,bank);assert.equal(n.balances.仮払消費税等,s.balances.仮払消費税等);assert.equal(n.assets.find(a=>a.id===p.id).cost,E.gross(s,p.building));check(run(n));});
test('v43 final tax settles late evidence and restores concealed inventory before scoring',()=>{let s=rich();s.turn=109;s.history=s.history.filter(h=>h.turn<109);s=X.chooseTaxPolicy(s,['skim','inventory','defer']);let r;for(let t=109;t<=120;t++){r=run(s);check(r);s=r.state;if(t<120)s=E.next(E.compact(s));}assert(s.expansion.finalTaxSettled);assert(!s.taxEvidence.some(e=>['open','auditPending'].includes(e.status)));assert(!s.taxAudits.some(a=>a.status==='pending'));assert.equal(s.expansion.concealedInventory,0);assert.equal(s.balances.繰延売上,0);assert(X.score(s));});
test('v43 boat closure and charter, transfer wage preservation, replay and exit atomicity',()=>{let s=X.buyFishery(rich(),0,bank);s.actionLocked=null;s.expansion.fishery.crew=[{id:'crew-1',role:'captain',characterId:'madai',wage:350000,hiredTurn:24},{id:'crew-2',role:'crew',characterId:null,wage:180000,hiredTurn:24}];s=X.setBoatUse(s,'charter');const quote=X.charterPlan(s);assert(quote.passengers>0);let r=run(s);check(r);assert.equal(r.state.expansion.fishery.last.passengers,quote.passengers);s=E.next(r.state);s=X.setFishing(s,'rest');s=R.apply(s,{op:'transfer',args:['crew-2','store']}).state;assert.equal(E.payroll(s),180000);assert.equal(E.staffService(s.staff[0]),800);r=run(s);check(r);assert.equal(r.state.expansion.fishery.last.days,0);assert(!r.state.taxEvidence.some(e=>e.kind==='idleBoat'));assert(r.report.entries.some(e=>e.memo==='船の維持・修繕'&&e.amount===40000));s=E.next(r.state);const q=X.exitQuote(s,'fishery-boat');assert.deepEqual(X.exitQuote(s,'fishery-boat'),q);const before=JSON.stringify(s),failed=structuredClone(s);failed.balances.預金=-100000000;assert.throws(()=>X.exitBusiness(failed,'fishery-boat'));assert.equal(JSON.stringify(s),before);s=X.exitBusiness(s,'fishery-boat');assert.equal(s.expansion.fishery,null);assert.equal(s.balances.船舶,0);assert(s.balances.固定資産売却損>0);check(run(s));});
test('v43 property exit removes land/building/deposit and settles linked debt',()=>{let s=rich(),p=X.market(s)[0];s=X.buyProperty(s,p.id,1000000,bank);let r=run(s);s=E.next(r.state);r=run(s);s=E.next(r.state);const ordinary=E.ordinary(s.balances),q=X.exitQuote(s,p.id),cash=s.balances.預金;s=X.exitBusiness(s,p.id);assert.equal(s.balances.預金,cash+q.net);assert.equal(s.balances.土地,0);assert.equal(s.balances.賃貸建物,0);assert.equal(s.balances.預り敷金,0);assert.equal(s.loans[0].balance,0);assert.equal(E.ordinary(s.balances),ordinary);check(run(s));});
test('v43 management UI operations and saved transferred captain remain usable',()=>{const {bootDOM}=require('./helpers/dom.cjs'),ui=bootDOM();try{let s=rich();s.history=Array.from({length:24},(_,i)=>({turn:i+1,balances:{...s.balances}}));s=X.buyFishery(s,0,bank);s.actionLocked=null;s.expansion.fishery.crew=[{id:'crew-1',role:'captain',characterId:'madai',wage:350000,hiredTurn:24}];s=X.transferStaff(s,'crew-1','store');const payload={version:7,introComplete:true,state:s,lastReport:null,choice:{quantities:E.PRODUCTS.map(()=>0),price:'list',action:'tend'},seen:[]};assert.equal(Backup.decode(Backup.encode(payload)).state.staff[0].wage,350000);ui.run(`skipIntro();state=${JSON.stringify(s)};showDiversification()`);assert.match(ui.document.getElementById('shopDialogBody').textContent,/船へ異動|船の用途/);ui.click('[data-exit-preview="fishery-boat"]');assert.match(ui.document.getElementById('shopDialogBody').textContent,/売却損益/);ui.click('[data-exit-confirm="fishery-boat"]');assert.equal(ui.run('state.expansion.fishery'),null);assert.equal(ui.errors.length,0);}finally{ui.close();}});
test('v43 a failed reduction with insufficient repayment cash is atomic',()=>{let s=E.fundLoan(E.createState(),{amount:100000,rate:2,months:3,kind:'short'});s.turn=3;E.entry(s,'差入保証金','預金',s.balances.預金-10000,'test');const before=JSON.stringify(s);assert.throws(()=>B.renew(s,{...bank,eligible:false},0,50000));assert.equal(JSON.stringify(s),before);});
test('v43 excessive stock pays carrying cost while normal opening tutorial is unaffected',()=>{const s=rich(),before=s.entries.length;s.balances.商品=2000000;X.monthly(s);assert(s.entries.slice(before).some(e=>e.memo.includes('在庫保管費')&&e.amount===3750));});
test('v44 part-timers stay ashore; store staff who sail keep their wage and get a boarding allowance',()=>{let s=X.buyFishery(rich(),0,bank);s.actionLocked=null;s.staff=[{id:'staff-1',role:'parttime',wage:120000,hiredTurn:1,offerTurn:25,departTurn:49},{id:'staff-2',role:'employee',wage:250000,hiredTurn:1}];assert.throws(()=>X.transferStaff(s,'staff-1','boat'),/バイト/);s=X.transferStaff(s,'staff-2','boat');assert.equal(s.expansion.fishery.crew[0].wage,250000);assert.equal(s.expansion.fishery.crew[0].homeRole,'employee');const r=run(s);check(r);assert(r.report.entries.some(e=>e.memo.startsWith('乗船手当')&&e.amount===30000));});
