/* Bound to the same pure game engine as the browser. No client snapshots are trusted. */
const Replay=globalThis.ShopReplay,E=globalThis.ShopEngine;
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...extra}});
const sha=async text=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),n=>n.toString(16).padStart(2,'0')).join('');
const monthKey=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,7);
const seedFor=async scenario=>parseInt((await sha('que-finance-'+Replay.VERSION+'-'+scenario)).slice(0,8),16)||73129;
function playerCookie(request){const value=request.headers.get('Cookie')?.match(/(?:^|; )que_player=([a-f0-9]{64})(?:;|$)/)?.[1];return value||null;}
function freshCookie(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');}
async function actor(request){const token=playerCookie(request);return token?sha(token):null;}
async function body(request,max=40000){if(Number(request.headers.get('Content-Length')||0)>max)throw Object.assign(Error('送信内容が大きすぎます'),{status:413});const reader=request.body?.getReader();if(!reader)throw Object.assign(Error('内容がありません'),{status:400});let chunks=[],size=0;for(;;){const r=await reader.read();if(r.done)break;size+=r.value.byteLength;if(size>max){await reader.cancel();throw Object.assign(Error('送信内容が大きすぎます'),{status:413});}chunks.push(r.value);}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length;}try{return JSON.parse(new TextDecoder().decode(bytes));}catch{throw Object.assign(Error('送信形式が不正です'),{status:400});}}
function pack(s){E.compact(s);for(const e of s.entries){delete e.before;delete e.after;delete e.memo;delete e.bundled;}delete s.replay;return JSON.stringify(s);}
async function ownedRun(db,id,request){if(!/^[a-f0-9-]{36}$/.test(id))return null;const who=await actor(request);return who?db.prepare('SELECT * FROM verified_runs WHERE id = ? AND actor = ?').bind(id,who).first():null;}
async function rankedRows(db,scenario){
 let best=[];for(let offset=0;;offset+=100){const page=await db.prepare('SELECT id,name,snapshot,created FROM rankings WHERE scenario = ? ORDER BY id LIMIT 100 OFFSET ?').bind(scenario,offset).all();
  for(const row of page.results||[]){const score=Replay.rescoreSnapshot(JSON.parse(row.snapshot)).score;best.push({id:row.id,name:row.name,created:row.created,score:score.total,profitability:score.profitability,health:score.health,wealth:score.wealth});}
  best.sort((a,b)=>b.score-a.score||a.created-b.created||a.id.localeCompare(b.id));best=best.slice(0,30);if((page.results||[]).length<100)break;
 }return best;
}
async function api(request,env){if(!env.DB)return json({error:'ランキングを準備しています。セーブを残して後で再接続してください。'},503);const url=new URL(request.url),path=url.pathname,now=Date.now();
 if(request.method==='GET'&&path==='/api/scenario'){const scenario=monthKey();return json({scenario,seed:await seedFor(scenario),engine:Replay.VERSION});}
 if(request.method==='GET'&&path==='/api/ranking'){const scenario=url.searchParams.get('scenario')||monthKey();if(!/^\d{4}-\d{2}$/.test(scenario))return json({error:'シナリオが不正です'},400);return json({scenario,scoreModel:E.extension.SCORE_MODEL,rows:await rankedRows(env.DB,scenario)});}
 const detail=path.match(/^\/api\/ranking\/([a-f0-9-]{36})$/);if(request.method==='GET'&&detail){const row=await env.DB.prepare('SELECT name,scenario,snapshot FROM rankings WHERE id = ?').bind(detail[1]).first();return row?json({...row,snapshot:Replay.rescoreSnapshot(JSON.parse(row.snapshot))}):json({error:'記録がありません'},404);}
 if(request.method==='POST'){const origin=request.headers.get('Origin');if(origin!==url.origin)return json({error:'この画面から操作してください'},403);}
 if(request.method==='POST'&&path==='/api/start'){const data=await body(request);if(data.scenario!==monthKey())return json({error:'今月のシナリオを選び直してください'},409);const cookie=playerCookie(request)||freshCookie(),who=await sha(cookie),count=await env.DB.prepare('SELECT COUNT(*) AS n FROM verified_runs WHERE actor = ? AND created > ?').bind(who,now-86400000).first();if(count.n>=20)return json({error:'新規チャレンジは１日20回までです'},429);const id=crypto.randomUUID(),seed=await seedFor(data.scenario),state=Replay.create(seed);await env.DB.prepare('INSERT INTO verified_runs (id,actor,scenario,engine,seed,revision,state,created,updated) VALUES (?,?,?,?,?,0,?,?,?)').bind(id,who,data.scenario,Replay.VERSION,seed,pack(state),now,now).run();return json({id,seed,scenario:data.scenario,engine:Replay.VERSION,revision:0},200,{'Set-Cookie':`que_player=${cookie}; Secure; HttpOnly; SameSite=None; Partitioned; Path=/; Max-Age=31536000`});}
 const route=path.match(/^\/api\/run\/([a-f0-9-]{36})(?:\/(step|publish|withdraw))?$/);if(!route)return json({error:'見つかりません'},404);const run=await ownedRun(env.DB,route[1],request);if(!run)return json({error:'このブラウザのチャレンジ記録がありません'},404);if(run.engine!==Replay.VERSION)return json({error:'このチャレンジは旧ルールです。ゲームは続けられますが、公開順位への追加登録はできません。'},409);
 if(request.method==='GET'&&!route[2]){const s=JSON.parse(run.state);return json({revision:run.revision,turn:s.turn,closed:s.closed,lastHash:run.last_hash,score:E.extension.score(s)});}
 if(request.method==='POST'&&route[2]==='step'){const data=await body(request),hash=await sha(JSON.stringify(data.command));if(!Number.isInteger(data.revision)||data.revision<0)return json({error:'履歴番号が不正です'},400);if(data.revision+1===run.revision&&hash===run.last_hash)return json({revision:run.revision,duplicate:true});if(data.revision!==run.revision)return json({error:'別の操作が先に保存されました。再接続してください',revision:run.revision},409);if(run.revision>=2000)return json({error:'操作数の上限です'},400);
  let next;try{next=Replay.apply(JSON.parse(run.state),data.command).state;}catch(err){return json({error:err.message},422);}const encoded=pack(next);if(new TextEncoder().encode(encoded).length>1800000)return json({error:'記録が保存上限を超えました'},413);
  const result=await env.DB.batch([env.DB.prepare('UPDATE verified_runs SET state = ?, revision = revision + 1, last_hash = ?, updated = ? WHERE id = ? AND revision = ?').bind(encoded,hash,now,run.id,run.revision),env.DB.prepare('INSERT OR IGNORE INTO verified_operations (run_id,revision,operation,hash) SELECT id,revision,?,? FROM verified_runs WHERE id = ? AND revision = ? AND last_hash = ?').bind(JSON.stringify(data.command),hash,run.id,run.revision+1,hash)]);if(result[0].meta.changes!==1)return json({error:'同時に更新されました。再接続してください'},409);return json({revision:run.revision+1,turn:next.turn,closed:next.closed});
 }
 if(request.method==='POST'&&route[2]==='publish'){const data=await body(request),name=typeof data.name==='string'?data.name.trim():'';if(!/^[\p{L}\p{N} _ー・]{1,20}$/u.test(name))return json({error:'表示名は文字・数字・空白で20文字以内にしてください'},400);if(data.revision!==run.revision)return json({error:'未同期の操作があります。先に同期してください'},409);const s=JSON.parse(run.state),score=E.extension.score(s);if(!score||['offer','negotiate','confirm'].includes(s.expansion.ma?.phase))return json({error:'10年間を完走し、商談を終えてから登録できます'},422);const snapshot=Replay.snapshot(s),previous=await env.DB.prepare('SELECT snapshot FROM rankings WHERE actor = ? AND scenario = ?').bind(run.actor,run.scenario).first();if(previous&&Replay.rescoreSnapshot(JSON.parse(previous.snapshot)).score.total>score.total)return json({score:score.total,published:false,retainedBest:true});await env.DB.prepare('INSERT INTO rankings (id,actor,scenario,name,score,profitability,health,wealth,snapshot,created) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(actor,scenario) DO UPDATE SET id=excluded.id,name=excluded.name,score=excluded.score,profitability=excluded.profitability,health=excluded.health,wealth=excluded.wealth,snapshot=excluded.snapshot,created=excluded.created WHERE rankings.snapshot = ? OR excluded.score >= rankings.score').bind(run.id,run.actor,run.scenario,name,score.total,score.profitability,score.health,score.wealth,JSON.stringify(snapshot),now,previous?.snapshot||null).run();return json({score:score.total,published:true});}
 if(request.method==='POST'&&route[2]==='withdraw'){await env.DB.prepare('DELETE FROM rankings WHERE actor = ? AND scenario = ?').bind(run.actor,run.scenario).run();return json({withdrawn:true});}
 return json({error:'対応していない操作です'},405);
}
export default {async fetch(request,env){try{const path=new URL(request.url).pathname;if(path.startsWith('/api/'))return await api(request,env);if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405});if(env.ASSETS)return env.ASSETS.fetch(request);const file=SITE_FILES[path==='/'?'/index.html':path];if(!file)return new Response('Not found',{status:404});const headers={'Content-Type':file.type,'X-Content-Type-Options':'nosniff','Cache-Control':path.startsWith('/assets/')?'public, max-age=86400':'no-cache'};return new Response(request.method==='HEAD'?null:Uint8Array.from(atob(file.data),c=>c.charCodeAt(0)),{headers});}catch(err){console.error('game-api',err?.message);return json({error:err.status?err.message:'保存に失敗しました。ゲームのセーブを残して、再接続してください。'},err.status||503);}}};
